#!/usr/bin/env bash
_DIR="$(dirname $0)"
export MEMCACHED_IMAGE=${MEMCACHED_IMAGE:="$(awk -F '[ :]' '{print $2}' $_DIR/Dockerfile)"}
export MEMCACHED_IMAGE_VERSION=${MEMCACHED_IMAGE_VERSION:="$(awk -F '[ :]' '{print $3}' $_DIR/Dockerfile)"}
export MEMCACHED_ROOT=${MEMCACHED_ROOT:="$DOKKU_LIB_ROOT/services/memcached"}
export MEMCACHED_HOST_ROOT=${MEMCACHED_HOST_ROOT:=$MEMCACHED_ROOT}

export PLUGIN_UNIMPLEMENTED_SUBCOMMANDS=("backup" "backup-auth" "backup-deauth" "backup-schedule" "backup-schedule-cat" "backup-set-encryption" "backup-unschedule" "backup-unset-encryption" "clone" "export" "import")
export PLUGIN_COMMAND_PREFIX="memcached"
export PLUGIN_CONFIG_ROOT=${PLUGIN_CONFIG_ROOT:="$DOKKU_LIB_ROOT/config/$PLUGIN_COMMAND_PREFIX"}
export PLUGIN_DATA_ROOT=$MEMCACHED_ROOT
export PLUGIN_DATA_HOST_ROOT=$MEMCACHED_HOST_ROOT
export PLUGIN_DATASTORE_PORTS=(11211)
export PLUGIN_DATASTORE_WAIT_PORT=11211
export PLUGIN_DEFAULT_ALIAS="MEMCACHED"
export PLUGIN_DISABLE_PULL=${MEMCACHED_DISABLE_PULL:=}
export PLUGIN_DISABLE_PULL_VARIABLE="MEMCACHED_DISABLE_PULL"
export PLUGIN_ALT_ALIAS="DOKKU_MEMCACHED"
export PLUGIN_IMAGE=$MEMCACHED_IMAGE
export PLUGIN_IMAGE_VERSION=$MEMCACHED_IMAGE_VERSION
export PLUGIN_SCHEME="memcached"
export PLUGIN_SERVICE="Memcached"
export PLUGIN_VARIABLE="MEMCACHED"
export PLUGIN_BASE_PATH="$PLUGIN_PATH"
export PLUGIN_CONFIG_SUFFIX="config"
if [[ -n $DOKKU_API_VERSION ]]; then
  export PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi

export PLUGIN_BUSYBOX_IMAGE="busybox:1.31.1-uclibc"
export PLUGIN_AMBASSADOR_IMAGE="dokku/ambassador:0.3.3"
export PLUGIN_S3BACKUP_IMAGE="dokku/s3backup:0.10.3"
export PLUGIN_WAIT_IMAGE="dokku/wait:0.4.3"
