#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

memcached-clone-cmd() {
  [[ -z "$2" ]] && dokku_log_fail "Please specify a name for the service"
  [[ -z "$3" ]] && dokku_log_fail "Please specify a name for the new service"
  verify_service_name "$3"

  dokku_log_fail "Not yet implemented"
}

memcached-clone-cmd "$@"
